version: 2.1
jobs:
  build:
    docker: 
      - image: cimg/base:2020.11
      # - image: cimg/node:14.10.1
    resource_class: small
      #   auth:
      #     username: mydockerhub-user
      #     password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
      - run:
          name: Set variables
          command: |
            echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_ORG_NAME=smartpick' >> $BASH_ENV
            echo 'export IMAGE_NAME=frontend' >> $BASH_ENV
            echo 'export IMAGE_REPOSITORY_URL=registry.digitalocean.com/k6ps-container-registry' >> $BASH_ENV
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            docker build -t $IMAGE_ORG_NAME/$IMAGE_NAME:$TAG .
            echo $DIGITALOCEAN_REGISTRY_API_KEY | docker login -u $DIGITALOCEAN_REGISTRY_API_KEY --password-stdin $IMAGE_REPOSITORY_URL
            docker push $IMAGE_ORG_NAME/$IMAGE_NAME:$TAG
      # - run:
      #     name: Deploy app to Digital Ocean Server via Docker
      #     command: |
      #       ssh -o StrictHostKeyChecking=no k6ps@157.230.99.225 "/bin/bash ./deploy_app.sh $IMAGE_ORG_NAME/$IMAGE_NAME:$TAG"